In [17]:
import pandas as pd
import joblib

In [2]:
df = pd.read_csv('data/BIKE_DETAILS.csv')
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
0,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,NaN
1,Honda Dio,45000,2017,Individual,1st owner,5650,NaN
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
4,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,NaN

In [3]:
df.isnull().sum()

name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               1061 non-null   str
 1   selling_price      1061 non-null   int64
 2   year               1061 non-null   int64
 3   seller_type        1061 non-null   str
 4   owner              1061 non-null   str
 5   km_driven          1061 non-null   int64
 6   ex_showroom_price  626 non-null    float64
dtypes: float64(1), int64(3), str(3)
memory usage: 58.2 KB

In [5]:
print(df.duplicated().sum())

6

In [6]:
df.describe()

       selling_price         year      km_driven  ex_showroom_price
count    1061.000000  1061.000000    1061.000000       6.260000e+02
mean    59638.151744  2013.867107   34359.833176       8.795871e+04
std     56304.291973     4.301191   51623.152702       7.749659e+04
min      5000.000000  1988.000000     350.000000       3.049000e+04
25%     28000.000000  2011.000000   13500.000000       5.485200e+04
50%     45000.000000  2015.000000   25000.000000       7.275250e+04
75%     70000.000000  2017.000000   43000.000000       8.703150e+04
max    760000.000000  2020.000000  880000.000000       1.278000e+06

In [7]:
df.drop_duplicates(inplace=True)

df['ex_showroom_price'] = df['ex_showroom_price'].fillna(df['ex_showroom_price'].median())

df['bike_age'] = 2026 - df['year']
df.drop('year', axis=1, inplace=True)

owner_dict = {'1st owner' : 1, '2nd owner' : 2, '3rd owner' : 3, '4th owner' : 4}
df['owner'] = df['owner'].map(owner_dict).fillna(5)

df = pd.get_dummies(df, columns=['seller_type'], drop_first=True)

df_final = df.drop('name', axis=1)

df_final.head()

,selling_price,owner,km_driven,ex_showroom_price,bike_age,seller_type_Individual
0,175000,1,350,72752.5,7,True
1,45000,1,5650,72752.5,9,True
2,150000,1,12000,148114.0,8,True
3,65000,1,23000,89643.0,11,True
4,20000,2,21000,72752.5,15,True

In [8]:
print(df_final.isnull().sum())

selling_price             0
owner                     0
km_driven                 0
ex_showroom_price         0
bike_age                  0
seller_type_Individual    0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, VotingRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

In [10]:
X = df_final.drop('selling_price', axis=1)
Y = df_final['selling_price']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [11]:
model1 = LinearRegression()
model2 = RandomForestRegressor(n_estimators=100, random_state=42)
model3 = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)

ensemble_model = VotingRegressor([
    ('lr', model1),
    ('rf', model2),
    ('xgb', model3)
], weights=[1, 2, 5])

ensemble_model.fit(X_train, Y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('rf', RandomForestRegressor(random_state=42)),
                            ('xgb',
                             XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=Non...
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints=None,
                                          learning_rate=0.1, max_bin=None,
                                          max_cat_threshold=None,
                                          max_cat_to_onehot=None,
                                          max_delta_step=None, max_depth=None,
                                          max_leaves=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None, n_estimators=100,
                                          n_jobs=None, num_parallel_tree=None, ...))],
                weights=[1, 2, 5])

In [12]:
Y_pred = ensemble_model.predict(X_test)
print(f"R2 Score : {r2_score(Y_test, Y_pred) : .4f}")
print(f"Mean Absolute Error : {mean_absolute_error(Y_test, Y_pred) : .2f}")

R2 Score :  0.7826
Mean Absolute Error :  18006.54

In [18]:
joblib.dump(ensemble_model, 'model/bike_price_predict.pkl')

['model/bike_price_predict.pkl']